### ISSUE TITLE
Only 15 find() possible

### ISSUE THREAD

**Issue by giusef** [mtasuandi/PHPGoogleKeywordPosition#1]
Hi, I'm using your class to try to find position of 24 various keywords (and more) after 15 it's not find anymore.  Why?

Thank you for your code!!

Giuseppe

**Comment by giusef** [comment]
Also making a sleep(60) call after each find() does not resolve the issue.

**Comment by mtasuandi** [comment]
Hi giusef, try to increase $end in the constructor.

From:
public function __construct($start=1, $end=2)

To:
public function __construct($start=1, $end=5) or more

Thanks

**Comment by giusef** [comment]
This is not the point.  I can read your PHP code and understand that $end
is used as the maximum number of pages to extract. This is right but I need
another thing.  Since I'm checking several keywords for a single domain I
need to call find() with each of them.  So, after the 15th keyword I'm
checking (15th find() call) something stops (is it something on the Google
side to prevent that?) I'm also using sleep(60) between each find() call
(remember, different keyword).

What's that?

Thank you.
Giuseppe

2014/1/8 M Teguh A Suandi notifications@github.com

> Hi giusef, try to increase $end in the constructor.
> 
> From:
> public function __construct($start=1, $end=2)
> 
> To:
> public function __construct($start=1, $end=5) or more
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mtasuandi/PHPGoogleKeywordPosition/issues/1#issuecomment-31819044
> .

## 

```
  Giuseppe F.
```
-   Connecting infos*

**Comment by mtasuandi** [comment]
Maybe you can try to print any results returned by google not just an array returned by the PHP Class. Because sometimes google returned another error messages (that maybe these PHP Class can't handle).

M Teguh

**Comment by sugappriyaodessa** [comment]
Hi,

I got the ranking without proxy but if i am using  proxy its throwing captcha image and its not loaded with relative url.

Please help me to fix this issue
